name: Build Android and Desktop Apps

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission to gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: app/build/outputs/apk/debug/app-debug.apk

  build-desktop:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y autoconf bubblewrap git fakeroot

    - name: Grant execute permissions to build scripts
      run: chmod +x xinput_dev/*.sh

    - name: Clone Wine
      run: git clone --depth 1 --branch wine-9.3 https://github.com/wine-mirror/wine.git xinput_dev/work_temp/wine

    - name: Run bootstrap script
      run: fakeroot ./xinput_dev/create_ubuntu_bootstraps.sh

    - name: Prepare build environment
      run: ./xinput_dev/prepare.sh

    - name: Compile Xinput
      run: ./xinput_dev/compile_xinput.sh

    - name: Upload Xinput DLLs
      uses: actions/upload-artifact@v4
      with:
        name: xinput-dlls
        path: xinput_dev/output/