name: Build Android App and UDP Proxy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission to gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: app/build/outputs/apk/debug/app-debug.apk

  build-proxy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install build tools and cross-compiler
      run: sudo apt-get update && sudo apt-get install -y gcc make gcc-aarch64-linux-gnu

    - name: Compile the proxy for all architectures
      run: make -C proxy all

    - name: Prepare package directory
      run: |
        mkdir -p package/amd64
        mkdir -p package/arm64
        mv proxy/udp_proxy_amd64 package/amd64/udp_proxy
        mv proxy/udp_proxy_arm64 package/arm64/udp_proxy
        cp proxy/install-service.sh package/
        cp proxy/proxy.service package/

    - name: Upload Proxy Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: udp-proxy-package
        path: package/